name: oidc-smoke
on: [workflow_dispatch]
permissions:
  id-token: write
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/<YOUR_ROLE_NAME>
          aws-region: ap-northeast-1
      - run: aws sts get-caller-identity
